name: recipe_api
description: Recipe API package fetches data from the TheMealDb API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^0.2.0
  very_good_analysis: ^3.0.1
